<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Wyrmforge.Application/Wyrmforge.Application.csproj" />
    <ProjectReference Include="../Wyrmforge.Infrastructure/Wyrmforge.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
  </ItemGroup>
</Project>
